trigger: none

pr: none


resources:
  pipelines:
  - pipeline: ciartifacts
    source: mdwdops-ci-artifacts
    trigger: 
      branches:
      - main
  repositories:
  - repository: mdwdataops_adfpublish
    type: github
    endpoint: mdwdops-github
    name: arudraMS/DataOpsWorkshop
    ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
# variables:
#   devAdfName: <DEV DATAFACTORY NAME>
 
stages:
- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: mdwdops-prod-release
  jobs: 
  - template: templates/jobs/deploy-adf-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-prod-serviceconnection'
      
