trigger: none

pr: none

parameters:
- deploymentId: deploymentId
  type: string

resources:
  pipelines:
  - pipeline: ciartifacts
    source: mdwdops-${{ parameters.deploymentId}}-ci-artifacts
    trigger: 
      branches:
      - main
  repositories:
  - repository: mdwdataops_adfpublish
    type: github
    endpoint: mdwdops-dat1-github
    name: arudraMS/DataOpsWorkshop
    ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
# variables:
#   devAdfName: <DEV DATAFACTORY NAME>
 
stages:
- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: mdwdops-dat1-prod-release
  jobs: 
  - template: templates/jobs/deploy-adf-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-dat1-prod-serviceconnection'
      
