trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ciartifacts
    source: mdwdops-ci-artifacts
    trigger: 
      branches:
      - main
  repositories:
  - repository: mdwdataops_adfpublish
    type: github
    endpoint: mdwdops-github
    name: devlace/mdw-dataops-clone
    ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
# variables:
#   devAdfName: <DEV DATAFACTORY NAME>

stages:
- stage: deploy_to_dev
  displayName: 'Deploy to DEV'  # In DEV, excludes publishing to ADF as this is a manual publish step
  variables:
  - group: mdwdops-release-dev
  - group: mdwdops-secrets-dev
 

- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: mdwdops-release-prod
  - group: mdwdops-secrets-prod
  jobs: 
  - template: templates/jobs/deploy-adf-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-serviceconnection-prod'
