trigger:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - e2e_samples/parking_sensors/*

pr: none

variables:
  basePath: 'e2e_samples/parking_sensors'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: 'publish_artifacts'
  displayName: 'Publish Build Artifacts'
  jobs:
  - job: 'publish_static_artifacts'
    displayName: 'Publish Static Artifacts'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        PathtoPublish: '$(basePath)/adf/_scripts/deploymentadf.ps1'
        ArtifactName: 'adf_scripts'
      displayName: 'Publish ADF Scripts'
