name: upload pre & post processing powershell script
on: 
  workflow_dispatch:

jobs:
  build-dev-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: infrastructure/deploymentadf.ps1
        

