# on: [push]
name: Azure Infra
on: 
  workflow_dispatch:
  
jobs:
  build-dev-environment:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - name: Log in With Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy Bicep file in Dev resource Group
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: infrastructure/inframain.bicep
        parameters: 'environment="development" keyVaultName=${{ vars.AZURE_KEYVAULT }} spnClientID=${{ secrets.AZURE_CLIENT_ID1 }} userObjectID=${{ secrets.AZURE_CLIENT_ID2 }} ddataFactoryName=${{ vars.AZURE_DATA_FACTORY }} storageSKU=${{ vars.AZURE_STORAGE_SKU }} storageAccountName=${{ vars.AZURE_STORAGE_ACCOUNT }} deployStorage=${{ vars.DEPLOY_STORAGE }} deployADF=${{ vars.DEPLOY_ADF }} gitType=${{ vars.GIT_TYPE }} gitAccount=${{ vars.GIT_ACCOUNT }} gitProject=${{ vars.GIT_PROJECT }} gitRepo=${{ vars.GIT_REPO }} gitCollab=${{ vars.GIT_COLLAB_BRANCH }} gitFolder=${{ vars.GIT_FOLDER }}'
        failOnStdErr: false
  
  build-prod-environment:
    runs-on: ubuntu-latest
    environment: Prod
    needs: build-dev-environment
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - name: Log in With Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy Bicep file in Dev resource Group
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: infrastructure/inframain.bicep
        parameters: 'environment="production" keyVaultName=${{ vars.AZURE_KEYVAULT }} spnClientID=${{ secrets.AZURE_CLIENT_ID1 }} userObjectID=${{ secrets.AZURE_CLIENT_ID2 }} dataFactoryName=${{ vars.AZURE_DATA_FACTORY }} storageSKU=${{ vars.AZURE_STORAGE_SKU }} storageAccountName=${{ vars.AZURE_STORAGE_ACCOUNT }} deployStorage=${{ vars.DEPLOY_STORAGE }} deployADF=${{ vars.DEPLOY_ADF }}'
        failOnStdErr: false
        
